### ISSUE TITLE
Wasmer 1.0.0 seems incompatible

### ISSUE THREAD

**Issue by moshemalawach** [miracle2k/wasmbind#2]
The api changed a bit in wasmer 1.0.0, and the instance loading an assembly script yields this error with the helloworld example:

RuntimeError: Error while importing "env"."abort": unknown import. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [] })

using this code before yours:

from wasmer import engine, Store, Module, Instance
from wasmer_compiler_singlepass import Compiler
store = Store(engine.JIT(Compiler))
module = Module(store, open('hello.wasm', 'rb').read())
instance = Instance(module)

**Comment by FGasper** [comment]
@moshemalawach I see the same. It looks like env.abort just needs to be provided by default.

Beyond that, though, there’s a bug where it tries to iterate through the Exports object via JSON, which fails now. Exports isn’t an iterator, though, so I’m not sure the proper way to extract the names of all the WASM exports. I’m hoping to get an answer from the Wasmer folks.

The maintainer doesn’t seem to be responding here … a fork may be indicated.

**Comment by FGasper** [comment]
Request to (re-)add the ability to iterate through the Exports object: https://github.com/wasmerio/wasmer-python/issues/535

**Comment by moshemalawach** [comment]
> The maintainer doesn’t seem to be responding here … a fork may be indicated.

Yep... Do you want to do it?

**Comment by miracle2k** [comment]
> The maintainer doesn’t seem to be responding here … a fork may be indicated.

FWIW, I don't have a lot of time right now to work on this, but I'd be happy to merge pull requests sent along.

**Comment by FGasper** [comment]
The 1.0.0 release simply won’t allow what this module does AFAICT. I’ll see about sending a PR once that changes.

**Comment by Hywan** [comment]
`wasmer.Exports` now implements the Iterator Protocol, see https://github.com/wasmerio/wasmer-python/pull/536.

**Comment by FGasper** [comment]
> > The maintainer doesn’t seem to be responding here … a fork may be indicated.
> 
> FWIW, I don't have a lot of time right now to work on this, but I'd be happy to merge pull requests sent along.

@moshemalawach: I’ve submitted a PR that fixes the basic API compatibility. See what you think.

**Comment by moshemalawach** [comment]
Great, will test it, thanks!
